/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MealIdRouteImport } from './routes/meal.$id'
import { Route as ApiPublicDeviceWeightRouteImport } from './routes/api/public/device/weight'
import { Route as ApiPublicDeviceConnectRouteImport } from './routes/api/public/device/connect'
import { Route as ApiPublicDeviceCaptureRouteImport } from './routes/api/public/device/capture'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MealIdRoute = MealIdRouteImport.update({
  id: '/meal/$id',
  path: '/meal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceWeightRoute = ApiPublicDeviceWeightRouteImport.update({
  id: '/api/public/device/weight',
  path: '/api/public/device/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceConnectRoute = ApiPublicDeviceConnectRouteImport.update({
  id: '/api/public/device/connect',
  path: '/api/public/device/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeviceCaptureRoute = ApiPublicDeviceCaptureRouteImport.update({
  id: '/api/public/device/capture',
  path: '/api/public/device/capture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/meal/$id': typeof MealIdRoute
  '/api/public/device/capture': typeof ApiPublicDeviceCaptureRoute
  '/api/public/device/connect': typeof ApiPublicDeviceConnectRoute
  '/api/public/device/weight': typeof ApiPublicDeviceWeightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/meal/$id': typeof MealIdRoute
  '/api/public/device/capture': typeof ApiPublicDeviceCaptureRoute
  '/api/public/device/connect': typeof ApiPublicDeviceConnectRoute
  '/api/public/device/weight': typeof ApiPublicDeviceWeightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/meal/$id': typeof MealIdRoute
  '/api/public/device/capture': typeof ApiPublicDeviceCaptureRoute
  '/api/public/device/connect': typeof ApiPublicDeviceConnectRoute
  '/api/public/device/weight': typeof ApiPublicDeviceWeightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/history'
    | '/insights'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/meal/$id'
    | '/api/public/device/capture'
    | '/api/public/device/connect'
    | '/api/public/device/weight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/history'
    | '/insights'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/meal/$id'
    | '/api/public/device/capture'
    | '/api/public/device/connect'
    | '/api/public/device/weight'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/history'
    | '/insights'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/meal/$id'
    | '/api/public/device/capture'
    | '/api/public/device/connect'
    | '/api/public/device/weight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  MealIdRoute: typeof MealIdRoute
  ApiPublicDeviceCaptureRoute: typeof ApiPublicDeviceCaptureRoute
  ApiPublicDeviceConnectRoute: typeof ApiPublicDeviceConnectRoute
  ApiPublicDeviceWeightRoute: typeof ApiPublicDeviceWeightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal/$id': {
      id: '/meal/$id'
      path: '/meal/$id'
      fullPath: '/meal/$id'
      preLoaderRoute: typeof MealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/weight': {
      id: '/api/public/device/weight'
      path: '/api/public/device/weight'
      fullPath: '/api/public/device/weight'
      preLoaderRoute: typeof ApiPublicDeviceWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/connect': {
      id: '/api/public/device/connect'
      path: '/api/public/device/connect'
      fullPath: '/api/public/device/connect'
      preLoaderRoute: typeof ApiPublicDeviceConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/device/capture': {
      id: '/api/public/device/capture'
      path: '/api/public/device/capture'
      fullPath: '/api/public/device/capture'
      preLoaderRoute: typeof ApiPublicDeviceCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  MealIdRoute: MealIdRoute,
  ApiPublicDeviceCaptureRoute: ApiPublicDeviceCaptureRoute,
  ApiPublicDeviceConnectRoute: ApiPublicDeviceConnectRoute,
  ApiPublicDeviceWeightRoute: ApiPublicDeviceWeightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
